void telaSobre(void);
void telaPrincipal(void);
void telaEquipe(void);
void telaCadastro(void);
void telaEscolhacarta(void);
void telareusltado(void);
void telalogin(void);
void baralho(void);
char signo(int,int);